### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by neophob** [gpit2286/mailgun-es6#11]
When I want to send an email, I see this error:
```
    TypeError: Cannot read property 'hasOwnProperty' of undefined
        at MailGun._buildFormData (/Users/snip/node_modules/mailgun-es6/index.js:116:26)
        at MailGun._sendRequest (/Users/snip/node_modules/mailgun-es6/index.js:165:19)
        at MailGun.sendEmail (/Users/snip/node_modules/mailgun-es6/index.js:227:17)
```

**Comment by davorb** [comment]
So basically, you want to be able to send emails with no text body? Am I understanding you correctly?

**Comment by neophob** [comment]
Thats a valid case yes. For example if you send alert emails which contains only a subject.

**Comment by davorb** [comment]
I'll take a look at this later, during the week.

**Comment by gpit2286** [comment]
Sorry guys - life happened. Can you just send it with text as an empty string. I believe that explicitly telling it to send an empty string is better than creating an exception for no value.
